version: 1.4.0.{build}

os: Visual Studio 2015

branches:
  only:
  - UmbracoVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
- cmd: >-
    mkdir artifacts

    cd build\

    Call build.cmd

    cd..

    cd log4net.Azure\

    nuget pack log4net.Appender.Azure.nuspec -version %APPVEYOR_BUILD_VERSION% -OutputDirectory ..\artifacts

before_test:
- cmd: '"%programfiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'

artifacts:
- path: artifacts\*.nupkg