version: 1.4.0.{build}

os: Visual Studio 2015

branches:
  only:
  - UmbracoVersion
  - UmbracoVersion-Experimental

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
- cmd: >-
    mkdir artifacts

    cd build\

    Call build.cmd

    cd..

    cd log4net.Azure\

    nuget pack log4net.Appender.Azure.nuspec -version %APPVEYOR_BUILD_VERSION% -OutputDirectory ..\artifacts

before_test:
- cmd: '"%programfiles(x86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start'

artifacts:
- path: artifacts\*.nupkg

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/log4net-azure-umbraco/
    symbol_server: https://nuget.symbolsource.org/MyGet/log4net-azure-umbraco
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: UmbracoVersion
